### ISSUE TITLE
P2: Centers > Literacy Centers: Unable to create a new Literacy Center and not displaying current centers

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#220]
When you Save a New Literacy Center, you get this error:
Error in creating Literacy Center:Value cannot be null. Parameter name: String
Also notice that when you click on Centers > Literacy Centers to see the listing on the demo site, you get none in the list. It seems the filtering code is broken. Note that there are 4 ALP Centers and 6 Literacy Centers in the demo DB.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Please find below the list of encountered issues:
- If the user wants to create a new ALP/Literacy Center and selects "School" as ALP/Literacy Center Type and doesn't select a value for the "Center" field, he gets the following error message: "Error in creating ALP Center:Value cannot be null. Parameter name: String"
- The "Center" and "School" drop down lists are displaying the same centers and schools for both LEMIS and EACI modes.
- No popup delete confirmation dialogue is generated, when the user clicks on the "Delete" button.

**Comment by RaymondYounan** [comment]
Points 1 and 3 done
Point 2, the schools and centers are generic for all programs, they are not split by Education Type

**Comment by tannourynadine** [comment]
Tested today and found that the mentioned issues in my previous comment are still reproducible.

**Comment by tannourynadine** [comment]
Verified that the issues mentioned in my previous comment are no longer reproducible.
