### ISSUE TITLE
P2: School > An error message is generated when the user tries to update a School

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#80]
No error should be generated when the user tries to update a school and the information should be updated correctly.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Please find below the results for the modify schools functionality:
The fields that gets updated are:
-   School Name (English)
-   School Name (عربي)
-   School Name (كوردى)
-   School Census
-   School Founding Date
-   Directorate
-   Facility/Center/School Status

The fields that won’t get updated are:
-   Gender
-   Education Stage

I could not test the below fields since I don’t have access to the DB:
-   Environment Type
-   Building Ownership
-   Building Independence
-   Building Quality
-   Country
-   Governorate
-   District
-   Sub-District
-   Village
-   Ward
-   Lane
-   House No.
-   Address Line 1
-   Address Line 2
-   Address Nearest Point Mark
-   Latitude
-   Longitude
-   Phone No.
-   Mobile Phone No.
-   Fax No.
-   Website

**Please note that updating a school that belongs to Iraq to a different Country generates the following error: "Error getting the Governorates:undefined"**

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the fields that gets updated are:
-   School Name (English)
-   School Name (عربي)
-   School Name (كوردى)
-   School Census
-   School Founding Date
-   Directorate
-   Facility/Center/School Status
-   Gender

**However, the "Education Stage" field still doesn't get updated.**
Please note that updating a school that belongs to Iraq to a different Country generates the following error: "Error getting the Governorates:undefined"

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the fields that gets updated are:
- School Name (English)
- School Name (عربي)
- School Name (كوردى)
- School Census
- School Founding Date
- Directorate
- Facility/Center/School Status
- Gender
- Education Stage
